"""add cameras table

Revision ID: ca62692399c7
Revises: f40ebb794499
Create Date: 2026-08-18 18:55:26.989362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca62692399c7'
down_revision: Union[str, None] = 'f40ebb794499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rtsp_url', sa.String(length=1024), nullable=False),
    sa.Column('bim_model_id', sa.Uuid(), nullable=True),
    sa.Column('bim_element_guid', sa.String(length=64), nullable=True),
    sa.Column('bim_zone_label', sa.String(length=255), nullable=True),
    sa.Column('world_position', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', name='camerastatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('frame_skip', sa.Integer(), nullable=False),
    sa.Column('auto_detect_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_detect_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_detection_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_defects_found', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bim_model_id'], ['bim_models.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cameras')
    # ### end Alembic commands ###
